In [2]:
# 1. Convert the below at its numpy array then display the array.
my_list=[1,2,3,4,5]


In [1]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
array = np.array(my_list)
print(array)

[1 2 3 4 5]


In [4]:
# 2. Convert the below list into a numpy array then display the array than display the first and last indes and then multiply each element by 2 and display the result my list=[1,2,3,4,5]

In [5]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("Original array:", my_array)
print("First index:", my_array[0])
print("Last index:", my_array[-1])
multiplied_array = my_array * 2
print("Array after multiplication by 2:", multiplied_array)



Original array: [1 2 3 4 5]
First index: 1
Last index: 5
Array after multiplication by 2: [ 2  4  6  8 10]


In [6]:
# 3. write a numpy program to create array of 10 zeros 10 ones and 10 fives .

In [16]:
import numpy as np
a=np.zeros(10,)
           
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
import numpy as np
a=np.ones(10,)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
import numpy as np
a=np.ones(10,)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [17]:
# 4. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [18]:
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
