In [1]:
# 1. Find days where the temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees Celsius (cold day).
import numpy as np
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])
hot_days = temperatures > 35
cold_days = temperatures < 5
extreme_days = hot_days
extreme_temperatures = temperatures[extreme_days]
extreme_indices = np.where(extreme_days)[0]
cold_temperatures = temperatures[cold_days]
cold_indices = np.where(cold_days)[0]
print("Hot Days")
print("Days")
print(extreme_indices+1)
print("temperatures")
print(extreme_temperatures)
print("cold Days")
print("Days")
print(cold_indices+1)
print("temperatures")
print(cold_temperatures)

Hot Days
Days
[ 3  6 10]
temperatures
[36.8 38.7 37.2]
cold Days
Days
[]
temperatures
[]


In [2]:
# 2. split this data into quarterly reports for analysis and reporting purposes.
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])
quarters = monthly_sales.reshape(4,3)
for i,quarter in enumerate(quarters,start=1):
    print(f"Quarter {i} sales:\n {quarter}")

Quarter 1 sales:
 [120 135 148]
Quarter 2 sales:
 [165 180 155]
Quarter 3 sales:
 [168 190 205]
Quarter 4 sales:
 [198 210 225]


In [3]:
# 3. split this data into two groups: one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days.
customer_ids = np.array([101,102,103,104,105,106,107,108,109,110])
last_purchase_days_ago = np.array([5,15,20,25,30,35,40,45,50,55])
recent_customers = customer_ids[last_purchase_days_ago <= 30]
inactive_customers = customer_ids[last_purchase_days_ago > 30]
print("Active customers ( last purchase <= 30 days ago):\n", recent_customers)
print("Inactive customers ( last purchase > 30 days ago):\n", inactive_customers)

Active customers ( last purchase <= 30 days ago):
 [101 102 103 104 105]
Inactive customers ( last purchase > 30 days ago):
 [106 107 108 109 110]


In [3]:
# 4. combine this data to create a comprehensive employee dataset for HR analysis.
import numpy as np
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])
result = np.concatenate((full_time_employees,part_time_employees),axis=0)
print(result)

[['101' 'John Doe' 'Full-Time' '55000']
 ['102' 'Jane Smith' 'Full-Time' '60000']
 ['103' 'Mike Johnson' 'Full-Time' '52000']
 ['201' 'Alice Brown' 'Part-Time' '25000']
 ['202' 'Bob Wilson' 'Part-Time' '28000']
 ['203' 'Emily Davis' 'Part-Time' '22000']]


In [13]:
# 5. find the mean of every NumPy array in the given list
import numpy as np
list = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]
for arr in list:
    mean = np.mean(arr)
    print("mean of ",arr,": ",mean)

mean of  [3 2 8 9] :  5.5
mean of  [ 4 12 34 25 78] :  30.6
mean of  [23 12 67] :  34.0


In [9]:
# 6. Compute the median of the flattened NumPy array
import numpy as np
x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
median = np.median(x_odd)
print("median : ",median)

median :  4.0


In [7]:
# 7. Compute the standard deviation of the NumPy array
import numpy as np
arr = [20, 2, 7, 1, 34]
SD = np.std(arr)
print("standard deviation : ",SD)

standard deviation :  12.576167937809991


In [14]:
# 8. Suppose you have a CSV file named 'house_prices.csv' with price information, and you want to perform the following operations:
import numpy as np
import pandas as pd

# 8.1. Read the data from the CSV file into a NumPy array
df = pd.read_csv('house_prices.csv')
prices = df['price'].to_numpy()

# 8.2. Calculate the average of house prices
average_price = np.mean(prices)

# 8.3. Identify house prices above the average
high_prices = prices[prices > average_price]

# 8.4. Save the list of high prices to a new CSV file
high_prices_df = pd.DataFrame(high_prices, columns=['High Price'])
high_prices_df.to_csv('high_prices.csv', index=False)

print("Average Price:", average_price)
print("High Prices:", high_prices)


Average Price: 317857.14285714284
High Prices: [400000 350000 500000]
